--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2025-03-10 16:15:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4873 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 53943)
-- Name: tbl_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_accounts (
    acc_code integer NOT NULL,
    acc_balance numeric(16,2) NOT NULL,
    acc_description character varying(255) NOT NULL,
    cli_code character varying(255) NOT NULL,
    acc_number character varying(25) NOT NULL,
    acc_state character varying(255) NOT NULL,
    acc_type character varying(25) NOT NULL
);


ALTER TABLE public.tbl_accounts OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 53942)
-- Name: tbl_accounts_acc_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_accounts ALTER COLUMN acc_code ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_accounts_acc_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 53860)
-- Name: tbl_clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_clients (
    cli_codigo character varying(25) NOT NULL,
    cli_passwo character varying(255) NOT NULL,
    cli_state character(1) NOT NULL,
    per_codigo integer
);


ALTER TABLE public.tbl_clients OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 53951)
-- Name: tbl_movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_movements (
    id bigint NOT NULL,
    mov_balance numeric(16,2) NOT NULL,
    mov_date date NOT NULL,
    mov_state character varying(25) NOT NULL,
    mov_type character varying(25) NOT NULL,
    mov_value numeric(16,2) NOT NULL,
    acc_code integer NOT NULL
);


ALTER TABLE public.tbl_movements OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 53950)
-- Name: tbl_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 53868)
-- Name: tbl_persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tbl_persons (
    per_codigo integer NOT NULL,
    per_age smallint NOT NULL,
    per_direcc character varying(255) NOT NULL,
    per_gender character varying(25) NOT NULL,
    per_identi character varying(255) NOT NULL,
    per_name character varying(255) NOT NULL,
    per_phone character varying(15) NOT NULL
);


ALTER TABLE public.tbl_persons OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 53867)
-- Name: tbl_persons_per_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tbl_persons ALTER COLUMN per_codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_persons_per_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4865 (class 0 OID 53943)
-- Dependencies: 219
-- Data for Name: tbl_accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_accounts VALUES (1, 7900.00, 'Datos adicionales', 'bchamba', '754256', 'A', 'AHORRO');


--
-- TOC entry 4861 (class 0 OID 53860)
-- Dependencies: 215
-- Data for Name: tbl_clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_clients VALUES ('bchamba', '091914092bc', 'A', 1);


--
-- TOC entry 4867 (class 0 OID 53951)
-- Dependencies: 221
-- Data for Name: tbl_movements; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_movements VALUES (1, 7800.00, '2025-03-10', 'R', 'AHORROS', -1200.00, 1);
INSERT INTO public.tbl_movements VALUES (2, 7900.00, '2025-03-10', 'D', 'AHORROS', 100.00, 1);


--
-- TOC entry 4863 (class 0 OID 53868)
-- Dependencies: 217
-- Data for Name: tbl_persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_persons VALUES (1, 29, 'QUITO, PINTADO', 'MASCULINO', '0703887497', 'CHAMBA FREIRE BRYAN ALEJANDRO', '0995763136');


--
-- TOC entry 4874 (class 0 OID 0)
-- Dependencies: 218
-- Name: tbl_accounts_acc_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_accounts_acc_code_seq', 1, true);


--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 220
-- Name: tbl_movements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_movements_id_seq', 2, true);


--
-- TOC entry 4876 (class 0 OID 0)
-- Dependencies: 216
-- Name: tbl_persons_per_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tbl_persons_per_codigo_seq', 1, true);


--
-- TOC entry 4711 (class 2606 OID 53949)
-- Name: tbl_accounts tbl_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_accounts
    ADD CONSTRAINT tbl_accounts_pkey PRIMARY KEY (acc_code);


--
-- TOC entry 4703 (class 2606 OID 53885)
-- Name: tbl_clients tbl_clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_clients
    ADD CONSTRAINT tbl_clients_pkey PRIMARY KEY (cli_codigo);


--
-- TOC entry 4715 (class 2606 OID 53955)
-- Name: tbl_movements tbl_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_movements
    ADD CONSTRAINT tbl_movements_pkey PRIMARY KEY (id);


--
-- TOC entry 4707 (class 2606 OID 53874)
-- Name: tbl_persons tbl_persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_persons
    ADD CONSTRAINT tbl_persons_pkey PRIMARY KEY (per_codigo);


--
-- TOC entry 4705 (class 2606 OID 53876)
-- Name: tbl_clients uke4c4b4c0yptwnjp45cdtu36da; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_clients
    ADD CONSTRAINT uke4c4b4c0yptwnjp45cdtu36da UNIQUE (per_codigo);


--
-- TOC entry 4713 (class 2606 OID 53957)
-- Name: tbl_accounts ukeqnckt7hybdukgvreymsm2vbf; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_accounts
    ADD CONSTRAINT ukeqnckt7hybdukgvreymsm2vbf UNIQUE (acc_number);


--
-- TOC entry 4709 (class 2606 OID 53878)
-- Name: tbl_persons uksdk2ie4d0c0elmu0ns26gvd3i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_persons
    ADD CONSTRAINT uksdk2ie4d0c0elmu0ns26gvd3i UNIQUE (per_identi);


--
-- TOC entry 4716 (class 2606 OID 53879)
-- Name: tbl_clients fk87v3xm3yeicjugodgfvb9cqct; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_clients
    ADD CONSTRAINT fk87v3xm3yeicjugodgfvb9cqct FOREIGN KEY (per_codigo) REFERENCES public.tbl_persons(per_codigo);


--
-- TOC entry 4717 (class 2606 OID 53958)
-- Name: tbl_movements fkstw7uyhumneb7h67htoqp59b5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tbl_movements
    ADD CONSTRAINT fkstw7uyhumneb7h67htoqp59b5 FOREIGN KEY (acc_code) REFERENCES public.tbl_accounts(acc_code);


-- Completed on 2025-03-10 16:15:22

--
-- PostgreSQL database dump complete
--

